"""Read/write named notion2tex profiles in a global config directory.

Kept dependency-light on purpose: only tomllib/tomli (no questionary here),
so a normal conversion that never touches --config doesn't need to import
anything beyond the standard library for this part of the pipeline.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib

# Keys understood by a profile, in the order they're written.
KEYS = (
    "book",
    "lang",
    "dark",
    "offline",
    "output",
    "font",
    "font_size",
    "paper",
    "margins",
    "accent_color",
)

_ACTIVE_MARKER = ".active"
_PROFILE_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def config_dir() -> Path:
    """
    Global directory profiles live in (created if missing). Never the
    directory notion2tex is run from -- that's the whole point of moving
    to named profiles instead of a per-folder notion2tex.toml.

    Respects XDG_CONFIG_HOME if set (also how the Docker wrapper scripts
    make profiles persist: they mount the host's config dir to a
    container path exported as XDG_CONFIG_HOME in the Dockerfile).
    """
    if xdg := os.environ.get("XDG_CONFIG_HOME"):
        base = Path(xdg)
    elif os.name == "nt":
        base = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming"))
    else:
        base = Path.home() / ".config"
    d = base / "notion2tex"
    d.mkdir(parents=True, exist_ok=True)
    return d


def validate_profile_name(name: str) -> str:
    name = name.strip()
    if not name or not _PROFILE_NAME_RE.fullmatch(name):
        raise ValueError(
            "profile name must be non-empty and use only letters, digits, - or _"
        )
    return name


def profile_path(name: str) -> Path:
    return config_dir() / f"{name}.toml"


def list_profiles() -> list[str]:
    """Names of all saved profiles, sorted."""
    return sorted(p.stem for p in config_dir().glob("*.toml"))


def get_active_profile() -> str | None:
    """
    The currently-active profile's name, or None if none is set (or the
    marker points at a profile that's since been deleted).
    """
    marker = config_dir() / _ACTIVE_MARKER
    if not marker.is_file():
        return None
    name = marker.read_text(encoding="utf-8").strip()
    return name if name and profile_path(name).is_file() else None


def set_active_profile(name: str | None) -> None:
    marker = config_dir() / _ACTIVE_MARKER
    if name is None:
        marker.unlink(missing_ok=True)
    else:
        marker.write_text(name, encoding="utf-8")


def delete_profile(name: str) -> None:
    profile_path(name).unlink(missing_ok=True)
    if get_active_profile() == name:
        set_active_profile(None)


def load_config(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def _format_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return '"' + str(value).replace('"', '\\"') + '"'


def write_config(path: Path, config: dict) -> None:
    """
    Write *config* as TOML, one line per key present in *config* (and only
    those in KEYS). Keys the user left at "no preference" are simply
    omitted rather than written as false/null -- keeps the file short and
    self-documenting: everything in it is something you actually chose.
    """
    lines = ["# notion2tex profile -- generated by `notion2tex --config`\n"]
    for key in KEYS:
        if key in config and config[key] is not None:
            lines.append(f"{key} = {_format_value(config[key])}\n")
    path.write_text("".join(lines), encoding="utf-8")


def validate_accent_color(value: str) -> str:
    """6 hex digits, optional leading '#'. Raises ValueError if invalid."""
    digits = value.lstrip("#")
    if len(digits) != 6 or any(c not in "0123456789abcdefABCDEF" for c in digits):
        raise ValueError(
            f"invalid hex color: {value!r} (expected 6 hex digits, e.g. 2E86AB or #2E86AB)"
        )
    return digits.upper()
