"""Read/write the optional notion2tex.toml config file (export defaults).

Kept dependency-light on purpose: only tomllib/tomli (no questionary here),
so a normal conversion that never touches --config doesn't need to import
anything beyond the standard library for this part of the pipeline.
"""

from __future__ import annotations

from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib

CONFIG_FILENAME = "notion2tex.toml"

# Keys understood by the config file, in the order they're written.
KEYS = (
    "book",
    "lang",
    "dark",
    "offline",
    "output",
    "font",
    "font_size",
    "paper",
    "margins",
    "accent_color",
)


def find_config(directory: Path) -> Path | None:
    """Return the config file in *directory*, if present."""
    path = directory / CONFIG_FILENAME
    return path if path.is_file() else None


def load_config(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def _format_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return '"' + str(value).replace('"', '\\"') + '"'


def write_config(path: Path, config: dict) -> None:
    """
    Write *config* as TOML, one line per key present in *config* (and only
    those in KEYS). Keys the user left at "no preference" are simply
    omitted rather than written as false/null -- keeps the file short and
    self-documenting: everything in it is something you actually chose.
    """
    lines = ["# notion2tex export defaults -- generated by `notion2tex --config`\n"]
    for key in KEYS:
        if key in config and config[key] is not None:
            lines.append(f"{key} = {_format_value(config[key])}\n")
    path.write_text("".join(lines), encoding="utf-8")


def validate_accent_color(value: str) -> str:
    """6 hex digits, optional leading '#'. Raises ValueError if invalid."""
    digits = value.lstrip("#")
    if len(digits) != 6 or any(c not in "0123456789abcdefABCDEF" for c in digits):
        raise ValueError(
            f"invalid hex color: {value!r} (expected 6 hex digits, e.g. 2E86AB or #2E86AB)"
        )
    return digits.upper()
